Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Prgfx.Neos.TextPartLanguage':
            resource: resource://Prgfx.Neos.TextPartLanguage/Public/JavaScript/TextPartLanguage/Plugin.js
      frontendConfiguration:
        'Prgfx.Neos.TextPartLanguage:languages': ${Configuration.setting('Neos.Neos.userInterface.availableLanguages')}
    userInterface:
      translation:
        autoInclude:
          'Prgfx.Neos.TextPartLanguage':
            - 'Editor'
    fusion:
      autoInclude:
        'Prgfx.Neos.TextPartLanguage': true
